apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      env: test
  template:
    metadata:
      labels:
        env: test
    spec:
      containers:
        - name: gg-deploy
          image: gcr.io/google-samples/hello-app:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
