apiVersion: v1
kind: Service
metadata:
  name: google-deployment
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    env: test
